/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

import javax.swing.JOptionPane;

/**
 *
 * @author Mane
 */
public class Ventana extends javax.swing.JInternalFrame {
        int c=0, c2=0;
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        btn_calcular = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        btn_cerrar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btn_suma = new javax.swing.JButton();
        btn_resta = new javax.swing.JButton();
        btn_multiplicacion = new javax.swing.JButton();
        btn_division = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        opt_suma = new javax.swing.JRadioButton();
        opt_resta = new javax.swing.JRadioButton();
        opt_multiplicacion = new javax.swing.JRadioButton();
        opt_divicion = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        txt_1 = new javax.swing.JTextField();
        txt_2 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        lbl_resultado = new javax.swing.JLabel();

        setClosable(true);

        jPanel2.setPreferredSize(new java.awt.Dimension(418, 50));
        jPanel2.setLayout(new java.awt.GridLayout(1, 1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Operaciónes Aritmeticas");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setPreferredSize(new java.awt.Dimension(431, 50));
        jPanel3.setLayout(new java.awt.GridLayout(1, 4));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel7);

        jPanel8.setLayout(new java.awt.GridLayout(1, 1));

        btn_calcular.setText("Calcular");
        btn_calcular.setEnabled(false);
        btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularActionPerformed(evt);
            }
        });
        jPanel8.add(btn_calcular);

        jPanel3.add(jPanel8);

        jPanel9.setLayout(new java.awt.GridLayout(1, 1));

        btn_cerrar.setText("Cerrar");
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });
        jPanel9.add(btn_cerrar);

        jPanel3.add(jPanel9);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel6);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel4.setPreferredSize(new java.awt.Dimension(110, 162));
        jPanel4.setLayout(new java.awt.GridLayout(4, 1));

        btn_suma.setText("Suma");
        btn_suma.setEnabled(false);
        btn_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sumaActionPerformed(evt);
            }
        });
        jPanel4.add(btn_suma);

        btn_resta.setText("Resta");
        btn_resta.setToolTipText("");
        btn_resta.setEnabled(false);
        btn_resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_restaActionPerformed(evt);
            }
        });
        jPanel4.add(btn_resta);

        btn_multiplicacion.setText("Multiplicacíón");
        btn_multiplicacion.setEnabled(false);
        btn_multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multiplicacionActionPerformed(evt);
            }
        });
        jPanel4.add(btn_multiplicacion);

        btn_division.setText("Division");
        btn_division.setEnabled(false);
        btn_division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_divisionActionPerformed(evt);
            }
        });
        jPanel4.add(btn_division);

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_END);

        jPanel5.setPreferredSize(new java.awt.Dimension(110, 162));
        jPanel5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPanel5KeyTyped(evt);
            }
        });
        jPanel5.setLayout(new java.awt.GridLayout(4, 1));

        buttonGroup1.add(opt_suma);
        opt_suma.setSelected(true);
        opt_suma.setText("Suma");
        opt_suma.setToolTipText("");
        opt_suma.setEnabled(false);
        opt_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt_sumaActionPerformed(evt);
            }
        });
        jPanel5.add(opt_suma);

        buttonGroup1.add(opt_resta);
        opt_resta.setText("Resta");
        opt_resta.setEnabled(false);
        jPanel5.add(opt_resta);

        buttonGroup1.add(opt_multiplicacion);
        opt_multiplicacion.setText("Multiplicación");
        opt_multiplicacion.setEnabled(false);
        jPanel5.add(opt_multiplicacion);

        buttonGroup1.add(opt_divicion);
        opt_divicion.setText("Divición");
        opt_divicion.setEnabled(false);
        jPanel5.add(opt_divicion);

        getContentPane().add(jPanel5, java.awt.BorderLayout.LINE_START);

        jPanel1.setLayout(new java.awt.GridLayout(4, 1));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel10);

        txt_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_1KeyTyped(evt);
            }
        });
        jPanel1.add(txt_1);

        txt_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_2ActionPerformed(evt);
            }
        });
        txt_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_2KeyTyped(evt);
            }
        });
        jPanel1.add(txt_2);

        jPanel11.setLayout(new java.awt.GridLayout(1, 1));

        lbl_resultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_resultado.setText("0.0");
        jPanel11.add(lbl_resultado);

        jPanel1.add(jPanel11);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opt_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt_sumaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt_sumaActionPerformed

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
            this.hide();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void txt_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_1KeyTyped
        // TODO add your handling code here:

        int key = evt.getKeyChar(); //convertir un char a ascii//
        
        if (key >=48 && key<=57){
        c++;
        }else{
        evt.consume();
        }
        if (c>0 && c2>=0 ){
        btn_suma.setEnabled(true);
        btn_multiplicacion.setEnabled(true);
        btn_division.setEnabled(true);
        btn_resta.setEnabled(true);
        }else{
        btn_suma.setEnabled(false);
        btn_multiplicacion.setEnabled(false);
        btn_division.setEnabled(false);
        btn_resta.setEnabled(false);
        }
        if(key==8){
    c--;
    }
    }//GEN-LAST:event_txt_1KeyTyped

    private void txt_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_2ActionPerformed

    private void txt_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_2KeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar(); //convertir un char a ascii//
        
        if (key >=48 && key<=57){
        c2++;
        }else{
        evt.consume();
        }
        if (c>=0 && c2>=0 ){
        btn_suma.setEnabled(true);
        btn_multiplicacion.setEnabled(true);
        btn_division.setEnabled(true);
        btn_resta.setEnabled(true);
        }else{
        btn_suma.setEnabled(false);
        btn_multiplicacion.setEnabled(false);
        btn_division.setEnabled(false);
        btn_resta.setEnabled(false);
        }
        if(key==8){
    c2--;
    }
    }//GEN-LAST:event_txt_2KeyTyped

    private void btn_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumaActionPerformed
        // TODO add your handling code here:
        String n1, n2;
        n1=txt_1.getText();
        n2=txt_2.getText();
        Validaciones v =new Validaciones();
        if(v.validarEnteros(n1).equals("decimal")){
        
            float a= Float.parseFloat(n1);
            if(v.validarEnteros(n2).equals("decimal")){
               float b = Float.parseFloat(n2);
               float r= a+b;
               lbl_resultado.setText(Float.toString(r));
            } else if (v.validarEnteros(n2).equals("entero"))
            {
                int b =Integer.parseInt(n2);
                float r =a+b;
                lbl_resultado.setText(Float.toString(r));
            }
            
        }else if (v.validarEnteros(n1).equals("entero")){
            int a= Integer.parseInt(n1);
            if (v.validarEnteros(n2).equals("entero")){
                int b= Integer.parseInt(n2);
                int r= a+b;
                lbl_resultado.setText(Integer.toString(r));
            }else if (v.validarEnteros(n2).equals("decimal")){
                float t = Float.parseFloat(n2);
                float r = a+t;
                lbl_resultado.setText(Float.toString(r));
                
            }
        }
        
    }//GEN-LAST:event_btn_sumaActionPerformed

    private void btn_restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restaActionPerformed
        // TODO add your handling code here:
        String n1, n2;
        n1=txt_1.getText();
        n2=txt_2.getText();
        Validaciones v =new Validaciones();
        if(v.validarEnteros(n1).equals("decimal")){
        
            float a= Float.parseFloat(n1);
            if(v.validarEnteros(n2).equals("decimal")){
               float b = Float.parseFloat(n2);
               float r= a-b;
               lbl_resultado.setText(Float.toString(r));
            } else if (v.validarEnteros(n2).equals("entero"))
            {
                int b =Integer.parseInt(n2);
                float r =a-b;
                lbl_resultado.setText(Float.toString(r));
            }
            
        }else if (v.validarEnteros(n1).equals("entero")){
            int a= Integer.parseInt(n1);
            if (v.validarEnteros(n2).equals("entero")){
                int b= Integer.parseInt(n2);
                int r= a-b;
                lbl_resultado.setText(Integer.toString(r));
            }else if (v.validarEnteros(n2).equals("decimal")){
                float t = Float.parseFloat(n2);
                float r = a-t;
                lbl_resultado.setText(Float.toString(r));
                
            }
        }
        
    }//GEN-LAST:event_btn_restaActionPerformed

    private void btn_multiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multiplicacionActionPerformed
        // TODO add your handling code here:
        String n1, n2;
        n1=txt_1.getText();
        n2=txt_2.getText();
        Validaciones v =new Validaciones();
        if(v.validarEnteros(n1).equals("decimal")){
        
            float a= Float.parseFloat(n1);
            if(v.validarEnteros(n2).equals("decimal")){
               float b = Float.parseFloat(n2);
               float r= a*b;
               lbl_resultado.setText(Float.toString(r));
            } else if (v.validarEnteros(n2).equals("entero"))
            {
                int b =Integer.parseInt(n2);
                float r =a*b;
                lbl_resultado.setText(Float.toString(r));
            }
            
        }else if (v.validarEnteros(n1).equals("entero")){
            int a= Integer.parseInt(n1);
            if (v.validarEnteros(n2).equals("entero")){
                int b= Integer.parseInt(n2);
                int r= a*b;
                lbl_resultado.setText(Integer.toString(r));
            }else if (v.validarEnteros(n2).equals("decimal")){
                float t = Float.parseFloat(n2);
                float r = a*t;
                lbl_resultado.setText(Float.toString(r));
                
            }
        }
        
    }//GEN-LAST:event_btn_multiplicacionActionPerformed

    private void btn_divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divisionActionPerformed
        // TODO add your handling code here:
        String n1, n2;
        n1=txt_1.getText();
        n2=txt_2.getText();
        Validaciones v =new Validaciones();
        if(v.validarEnteros(n1).equals("decimal")){
        
            float a= Float.parseFloat(n1);
            if(v.validarEnteros(n2).equals("decimal")){
               float b = Float.parseFloat(n2);
               float r= a/b;
               lbl_resultado.setText(Float.toString(r));
            } else if (v.validarEnteros(n2).equals("entero"))
            {
                int b =Integer.parseInt(n2);
                float r =a/b;
                lbl_resultado.setText(Float.toString(r));
            }
            
        }else if (v.validarEnteros(n1).equals("entero")){
            int a= Integer.parseInt(n1);
            if (v.validarEnteros(n2).equals("entero")){
                int b= Integer.parseInt(n2);
                int r= a/b;
                lbl_resultado.setText(Integer.toString(r));
            }else if (v.validarEnteros(n2).equals("decimal")){
                float t = Float.parseFloat(n2);
                float r = a/t;
                lbl_resultado.setText(Float.toString(r));
                
            }
        }
    }//GEN-LAST:event_btn_divisionActionPerformed

    private void btn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularActionPerformed
        // TODO add your handling code here:
        String n1 = txt_1.getText();
        String n2 = txt_2.getText();
        //SUMA
        if(opt_suma.isSelected()){
            int a= Integer.parseInt(n1);
            int b= Integer.parseInt(n2);
            int c= a+b;
            lbl_resultado.setText(Integer.toString(c));
        }
        //RESTA
         if(opt_resta.isSelected()){
            int a= Integer.parseInt(n1);
            int b= Integer.parseInt(n2);
            int c= a-b;
            lbl_resultado.setText(Integer.toString(c));
         }
         //MULTIPLICACION
         if(opt_multiplicacion.isSelected()){
            int a= Integer.parseInt(n1);
            int b= Integer.parseInt(n2);
            int c= a*b;
            lbl_resultado.setText(Integer.toString(c));
         }
         //DIVISION
         if(opt_divicion.isSelected()){
            float a= Float.parseFloat(n1);
            float b= Float.parseFloat(n2);
            float c= a/b;
            lbl_resultado.setText(Float.toString(c));
         }
    }//GEN-LAST:event_btn_calcularActionPerformed

    private void jPanel5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel5KeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar(); //convertir un char a ascii//
        
        if (key >=48 && key<=57){
        c2++;
        }else{
        evt.consume();
        }
        if (c>=0 && c2>=0 ){
        btn_suma.setEnabled(true);
        btn_multiplicacion.setEnabled(true);
        btn_division.setEnabled(true);
        btn_resta.setEnabled(true);
        }else{
        opt_suma.setEnabled(false);
        opt_multiplicacion.setEnabled(false);
        opt_divicion.setEnabled(false);
        btn_resta.setEnabled(false);
        }
        if(key==8){
    c2--;
    }
    }//GEN-LAST:event_jPanel5KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calcular;
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_division;
    private javax.swing.JButton btn_multiplicacion;
    private javax.swing.JButton btn_resta;
    private javax.swing.JButton btn_suma;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lbl_resultado;
    private javax.swing.JRadioButton opt_divicion;
    private javax.swing.JRadioButton opt_multiplicacion;
    private javax.swing.JRadioButton opt_resta;
    private javax.swing.JRadioButton opt_suma;
    private javax.swing.JTextField txt_1;
    private javax.swing.JTextField txt_2;
    // End of variables declaration//GEN-END:variables
}
